# -*- coding: utf-8 -*-
"""evidencia3_repositoriogithub.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NvrGdTGD60g58ieaf7aQEKCOw59tBzgk
"""

import pickle

objeto = {"nombre": "Julian", "edad": 30, "ciudad": "Monterrey N.L"}

with open("objeto.pickle", "wb") as archivo:
    pickle.dump(objeto, archivo)

with open("objeto.pickle", "rb") as archivo:
    objeto_recuperado = pickle.load(archivo)

print(objeto_recuperado)  #Salida: {'nombre': 'Julian', 'edad': 30, 'ciudad': 'Monterrey N.L'}